services:
  db:
    image: pgvector/pgvector:pg17
    container_name: name_generator_db
    environment:
      POSTGRES_DB: name_generator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - name_generator_pgdata:/var/lib/postgresql/data

volumes:
  name_generator_pgdata: