"""create generated name tables

Revision ID: 2abe38ec0e7b
Revises: 
Create Date: 2026-06-06 01:13:10.917237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2abe38ec0e7b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('meaning', sa.String(length=300), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('generation_flavors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('generated_name_flavors',
    sa.Column('generated_name_id', sa.Integer(), nullable=False),
    sa.Column('flavor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flavor_id'], ['generation_flavors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_name_id'], ['generated_names.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('generated_name_id', 'flavor_id')
    )
    op.create_table('generated_name_languages',
    sa.Column('generated_name_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['generated_name_id'], ['generated_names.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('generated_name_id', 'language_id')
    )
    op.create_table('name_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generated_name_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=100), nullable=False),
    sa.Column('meaning', sa.String(length=300), nullable=False),
    sa.Column('language', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['generated_name_id'], ['generated_names.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('name_parts')
    op.drop_table('generated_name_languages')
    op.drop_table('generated_name_flavors')
    op.drop_table('languages')
    op.drop_table('generation_flavors')
    op.drop_table('generated_names')
    # ### end Alembic commands ###
